products/urls.py
from django.urls import path,include
# from .api import product_list_api,product_detail
from .api import ProductDetail,ProductList,CategoryListAPI,CategoryDetail,BrandListApi,BrandDetail,ProductViewSet
from .views import Product_List,Product_Detail,BrandList,BrandDetail,CategoryList,add_review,product_list


from rest_framework import routers

router = routers.DefaultRouter()
router.register('myproducts',ProductViewSet)


app_name = "products"


urlpatterns = [
    path("testing/", product_list),
    path("", Product_List.as_view(), name="product_list"),
    path("brands/", BrandList.as_view(), name="brand_list"),
    path("category/", CategoryList.as_view(), name="category_list"),
    path("<int:pk>", Product_Detail.as_view(), name="product_detail"),
    path("<int:id>/review-add/",add_review, name="add_review"),
    path("brands/<int:pk>", BrandDetail.as_view(), name="brand_detail"),


    # path('api/list/',product_list_api),
    # path('api/list/<int:id>',product_detail),


    path('api/list/cbv/',ProductList.as_view()),
    path('api/list/cbv/<int:pk>',ProductDetail.as_view()),

    path('api/category/',CategoryListAPI.as_view()),
    path('api/brand/',BrandListApi.as_view()),
    path('api/category/<int:pk>/',CategoryDetail.as_view()),
    path('api/brand/<int:pk>/',BrandDetail.as_view()),

    path("myapi/",include(router.urls)),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("products/", include("products.urls", namespace="products")),
    path("__debug__/", include("debug_toolbar.urls")),

    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('i18n/',include('django.conf.urls.i18n')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models
from django.utils.translation import gettext as _
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.validators import MaxValueValidator, MinValueValidator
from taggit.managers import TaggableManager
from django.utils.text import slugify

# Create your models here.
FLAG_OPTION = (("New", "New"), ("Feature", "Feature"), ("Sale", "Sale"))


class Product(models.Model):
    name = models.CharField(_("Name"), max_length=100)
    subtitle = models.CharField(_("Subtitle"), max_length=500)
    sku = models.IntegerField(_("Sku"))
    desc = models.TextField(_("Description"), max_length=10000)
    price = models.FloatField(_("Price"))
    image = models.ImageField(_("Image"), upload_to="products/")
    flag = models.CharField(_("Flag"), max_length=10, choices=FLAG_OPTION)
    quantity = models.IntegerField(_("Quantity"))
    brand = models.ForeignKey(
        "Brand",
        related_name="product_brand",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )
    category = models.ForeignKey(
        "Category",
        related_name="product_category",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )
    tags = TaggableManager()
    slug = models.SlugField(null=True, blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Product, self).save(*args, **kwargs)


class ProductImages(models.Model):
    product = models.ForeignKey(
        Product, related_name="product_image", on_delete=models.CASCADE
    )
    image = models.ImageField(upload_to="product_images/")

    def __str__(self):
        return str(self.product)


class Brand(models.Model):
    name = models.CharField(_("Name"), max_length=50)
    image = models.ImageField(_("Image"), upload_to="brands/")
    category = models.ForeignKey(
        "Category",
        related_name="brand_category",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(_("Name"), max_length=50)
    image = models.ImageField(_("Image"), upload_to="categorys/")

    def __str__(self):
        return self.name


class ProductReview(models.Model):
    user = models.ForeignKey(
        User, related_name="user_review", verbose_name="User", on_delete=models.CASCADE
    )
    product = models.ForeignKey(
        Product,
        related_name="product_review",
        verbose_name="Product",
        on_delete=models.CASCADE,
    )
    rate = models.IntegerField(
        _("Rate"), validators=[MaxValueValidator(5), MinValueValidator(0)]
    )
    review = models.TextField(_("Review"), max_length=500)
    created_at = models.DateTimeField(_("Created at"), default=timezone.now)

    def __str__(self):
        return str(self.user)

products/forms.py
from django import forms 
from .models import ProductReview

class ReviewForm (forms.ModelForm):
  class Meta:
    model = ProductReview
    fields = ['review','rate']

products/views.py
from django.shortcuts import render,redirect
from .models import Product, Brand, Category
from django.views.generic import ListView, DetailView
from .forms import ReviewForm
from django.urls import reverse
from django.core.cache import cache
from django.views.decorators.cache import cache_page
from django.utils.decorators import method_decorator

# Create your views here.
@cache_page(60*2)
def product_list(request):
    products = Product.objects.all()
    return render(request,'products/product_list_test.html',{'products':products})

# def product_list(request):
#     if cache.get(['products']) is None:
#         products = Product.objects.all()
#         cache.set('products',products)
#     return render(request, "products/product_list_test.html", {"products": products})


class Product_List(ListView):
    model = Product
    paginate_by = 100


class Product_Detail(DetailView):
    model = Product


class BrandList(ListView):
    model = Brand

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = Category.objects.all()
        return context


class BrandDetail(DetailView):
    model = Brand

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        brand = self.get_object()
        context["brand_products"] = Product.objects.filter(brand=brand)
        return context


def add_review (request,id):
    product = Product.objects.get(id = id)
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            myform = form.save(commit=False)
            myform.user = request.user
            myform.product = product
            myform.save()
            return redirect(reverse('products:product_detail',kwargs={'id':id}))
        



class CategoryList(ListView):
    model = Category
    paginate_by = 10

products/templates/products/brand_detail.html
{% extends "base.html" %}
{% load static %}
{% block css %}

    <link rel="stylesheet" href=" {% static "css/brand-single.css" %} ">

{% endblock css %}
{% block body %}
        <!--=====================================
                    BANNER PART START
        =======================================-->
        <section class="single-banner" style="background: url({{brand.image.url}}) no-repeat center;">
            <div class="container">
                <h2>Brand Single</h2>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                    <li class="breadcrumb-item"><a href="brand-list.html">brand-list</a></li>
                    <li class="breadcrumb-item active" aria-current="page">brand-single</li>
                </ol>
            </div>
        </section>
        <!--=====================================
                    BANNER PART END
        =======================================-->


        <!--=====================================
                  BRAND SINGLE PART START
        =======================================-->
        <div class="brand-single">
            <a href="#"><img src="{{brand.image.url}}" alt="brand"></a>
            <a href="#"><h3>{{brand}}</h3></a>
            <ul>
                <li class="fas fa-star active"></li>
                <li class="fas fa-star active"></li>
                <li class="fas fa-star active"></li>
                <li class="fas fa-star active"></li>
                <li class="fas fa-star"></li>
                <li class="total">(163 ratings)</li>
            </ul>
            <p>(45 items)</p>
        </div>
        <!--=====================================
                  BRAND SINGLE PART END
        =======================================-->


        <!--=====================================
                    SHOP PART START
        =======================================-->
        <section class="inner-section shop-part">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="top-filter">
                            <div class="filter-show">
                                <label class="filter-label">Show :</label>
                                <select class="form-select filter-select">
                                    <option value="1">12</option>
                                    <option value="2">24</option>
                                    <option value="3">36</option>
                                </select>
                            </div>
                            <div class="filter-short">
                                <label class="filter-label">Short by :</label>
                                <select class="form-select filter-select">
                                    <option selected>default</option>
                                    <option value="3">trending</option>
                                    <option value="1">featured</option>
                                    <option value="2">recommend</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row row-cols-2 row-cols-md-3 row-cols-lg-3 row-cols-xl-5">

                    {% for product in brand_products %}
                    <div class="col">
                        <div class="product-card">
                            <div class="product-media">
                                <div class="product-label">
                                    <label class="label-text new">{{product.flag}}</label>
                                </div>
                                <button class="product-wish wish">
                                    <i class="fas fa-heart"></i>
                                </button>
                                <a class="product-image" href="product-video.html">
                                    <img src="{{product.image.url}}" alt="product">
                                </a>
                                <div class="product-widget">
                                    <a title="Product Compare" href="compare.html" class="fas fa-random"></a>
                                    <a title="Product Video" href="https://youtu.be/9xzcVxSBbG8" class="venobox fas fa-play" data-autoplay="true" data-vbtype="video"></a>
                                    <a title="Product View" href="#" class="fas fa-eye" data-bs-toggle="modal" data-bs-target="#product-view"></a>
                                </div>
                            </div>
                            <div class="product-content">
                                <div class="product-rating">
                                    <i class="active icofont-star"></i>
                                    <i class="active icofont-star"></i>
                                    <i class="active icofont-star"></i>
                                    <i class="active icofont-star"></i>
                                    <i class="icofont-star"></i>
                                    <a href="product-video.html">(3)</a>
                                </div>
                                <h6 class="product-name">
                                    <a href="product-video.html">{{product}}</a>
                                </h6>
                                <h6 class="product-price">
                                    <del>$34</del>
                                    <span>${{product.price}}<small>/piece</small></span>
                                </h6>
                                <button class="product-add" title="Add to Cart">
                                    <i class="fas fa-shopping-basket"></i>
                                    <span>add</span>
                                </button>
                                <div class="product-action">
                                    <button class="action-minus" title="Quantity Minus"><i class="icofont-minus"></i></button>
                                    <input class="action-input" title="Quantity Number" type="text" name="quantity" value="1">
                                    <button class="action-plus" title="Quantity Plus"><i class="icofont-plus"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="bottom-paginate">
                            <p class="page-info">Showing 12 of 60 Results</p>
                            <ul class="pagination">
                                <li class="page-item">
                                    <a class="page-link" href="#">
                                        <i class="fas fa-long-arrow-alt-left"></i>
                                    </a>
                                </li>
                                <li class="page-item"><a class="page-link active" href="#">1</a></li>
                                <li class="page-item"><a class="page-link" href="#">2</a></li>
                                <li class="page-item"><a class="page-link" href="#">3</a></li>
                                <li class="page-item">...</li>
                                <li class="page-item"><a class="page-link" href="#">60</a></li>
                                <li class="page-item">
                                    <a class="page-link" href="#">
                                        <i class="fas fa-long-arrow-alt-right"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--=====================================
                    SHOP PART END
        =======================================-->
        {% endblock body %}    

products/templates/products/brand_list.html
{% extends "base.html" %}
{% load static %}
{% block css %}

    <link rel="stylesheet" href=" {% static "css/brand-list.css" %} ">

{% endblock css %}
{% block body %}

        <!--=====================================
                    BANNER PART START
        =======================================-->
        <section class="inner-section single-banner" style="background: url(images/single-banner.jpg) no-repeat center;">
            <div class="container">
                <h2>brand list</h2>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">brand-list</li>
                </ol>
            </div>
        </section>
        <!--=====================================
                    BANNER PART END
        =======================================-->


        <!--=====================================
                    BRAND LIST PART START
        =======================================-->
        <section class="inner-section">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="top-filter">
                            <div class="filter-show">
                                <label class="filter-label">Show :</label>
                                <select class="form-select filter-select">
                                    <option value="1">12</option>
                                    <option value="2">24</option>
                                    <option value="3">36</option>
                                </select>
                            </div>
                            <div class="filter-short">
                                <label class="filter-label">Short by :</label>
                                <select class="form-select filter-select isotope-select">
                                    <option value="*">show all</option>
                                    {% for category in categories %}
                                    <option value=".{{category}}">{{category}}</option>
                                    {% endfor %}
                                    
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row row-cols-2 row-cols-md-3 row-cols-lg-4 row-cols-xl-5 isotope-items">
                    {% for brand in brand_list %}
                    <div class="col all {{brand.category}}">
                        <div class="brand-wrap">
                            <div class="brand-media">
                                <img src="{{brand.image.url}}" alt="brand">
                                <div class="brand-overlay">
                                    <a href="{% url "products:brand_detail" brand.id %}"><i class="fas fa-link"></i></a>
                                </div>
                            </div>
                            <div class="brand-meta">
                                <h4>{{brand}}</h4>
                                <p>(45 items)</p>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
              {% if is_paginated %}
                <div class="row">
                    <div class="col-lg-12">
                        <div class="bottom-paginate">
                            <p class="page-info">Showing 12 of 60 Results</p>
                            <ul class="pagination">
                              {% if page_obj.has_previous %}

                                <li class="page-item">
                                    <a class="page-link" href="?page={{page_obj.previous_page_number}}">
                                        <i class="fas fa-long-arrow-alt-left"></i>
                                    </a>
                                </li>
                              {% else %}
                                <li class="fas fa-long-arrow-alt-left disabled"></li>
                              {% endif %}

                              {% for i in paginator.page_range %}
                                {% if page_obj.number == i %}
                                  <li class="page-item"><a class="page-link active" href="#">{{i}}</a></li>
                                  
                                {% else %}
                                  <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
                                {% endif %}
                                
                              {% endfor %}
                              {% if page_obj.has_next %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{page_obj.next_page_number}}">
                                        <i class="fas fa-long-arrow-alt-right"></i>
                                    </a>
                                </li>
                              {% else %}
                                <li class="fas fa-long-arrow-alt-right disabled"></li>
                              {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
              {% endif %}
            </div>
        </section>
        <!--=====================================
                    BRAND LIST PART END
        =======================================-->

        {% endblock body %}

products/templates/products/category_list.html
{% extends "base.html" %}
{% block body %}
        <!--=====================================
                    BANNER PART START
        =======================================-->
        <section class="inner-section single-banner" style="background: url(images/single-banner.jpg) no-repeat center;">
            <div class="container">
                <h2>all category</h2>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">all-category</li>
                </ol>
            </div>
        </section>
        <!--=====================================
                    BANNER PART END
        =======================================-->


        <!--=====================================
                    CATEGORY PART START
        =======================================-->
        <section class="inner-section">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="top-filter">
                            <div class="filter-show">
                                <label class="filter-label">Show :</label>
                                <select class="form-select filter-select">
                                    <option value="1">12</option>
                                    <option value="2">24</option>
                                    <option value="3">36</option>
                                </select>
                            </div>
                            <div class="filter-short">
                                <label class="filter-label">Short by :</label>
                                <select class="form-select filter-select">
                                    <option selected>default</option>
                                    <option value="3">trending</option>
                                    <option value="1">featured</option>
                                    <option value="2">recommend</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row row-cols-2 row-cols-md-3 row-cols-lg-4 row-cols-xl-5 justify-content-center">
                    {% for cat in category_list %}
                    <div class="col">
                        <div class="category-wrap">
                            <div class="category-media">
                                <img src="{{cat.image.url}}" alt="category">
                                <div class="category-overlay">
                                    <a href="shop-3column.html"><i class="fas fa-link"></i></a>
                                </div>
                            </div>
                            <div class="category-meta">
                                <h4>{{cat}}</h4>
                                <p>(25 items)</p>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
              {% if is_paginated %}
                <div class="row">
                    <div class="col-lg-12">
                        <div class="bottom-paginate">
                            <p class="page-info">Showing 12 of 60 Results</p>
                            <ul class="pagination">
                              {% if page_obj.has_previous %}

                                <li class="page-item">
                                    <a class="page-link" href="?page={{page_obj.previous_page_number}}">
                                        <i class="fas fa-long-arrow-alt-left"></i>
                                    </a>
                                </li>
                              {% else %}
                                <li class="fas fa-long-arrow-alt-left disabled"></li>
                              {% endif %}

                              {% for i in paginator.page_range %}
                                {% if page_obj.number == i %}
                                  <li class="page-item"><a class="page-link active" href="#">{{i}}</a></li>
                                  
                                {% else %}
                                  <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
                                {% endif %}
                                
                              {% endfor %}
                              {% if page_obj.has_next %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{page_obj.next_page_number}}">
                                        <i class="fas fa-long-arrow-alt-right"></i>
                                    </a>
                                </li>
                              {% else %}
                                <li class="fas fa-long-arrow-alt-right disabled"></li>
                              {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
              {% endif %}
            </div>
        </section>
        <!--=====================================
                    CATEGORY PART END
        =======================================-->

        {% endblock body %}

products/templates/products/product_list_test.html
<ul>
    {% for product in products %} 
        <li>{{product}}</li>
    {% endfor %}
</ul>